2018-08-05 18:06:16,440 Exception on /edit_profile [POST] [in c:\users\kurt\appdata\local\programs\python\python37\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\kurt\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\kurt\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\kurt\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\kurt\appdata\local\programs\python\python37\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\kurt\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\kurt\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\kurt\appdata\local\programs\python\python37\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\kurt\Python\kurtain\kurtain\routes.py", line 76, in edit_profile
    return redirect(url_for('user', username = current_user[1]))
  File "c:\users\kurt\appdata\local\programs\python\python37\lib\site-packages\werkzeug\local.py", line 377, in <lambda>
    __getitem__ = lambda x, i: x._get_current_object()[i]
TypeError: 'User' object does not support indexing
2018-08-05 18:07:46,300 Kurtain Startup [in C:\Users\kurt\Python\kurtain\kurtain\__init__.py:42]
2018-08-05 18:08:33,870 Kurtain Startup [in C:\Users\kurt\Python\kurtain\kurtain\__init__.py:42]
2018-08-05 18:08:39,211 Exception on /edit_profile [POST] [in c:\users\kurt\appdata\local\programs\python\python37\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\kurt\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\kurt\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "c:\users\kurt\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1833, in finalize_request
    response = self.process_response(response)
  File "c:\users\kurt\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 2114, in process_response
    self.session_interface.save_session(self, ctx.session, response)
  File "c:\users\kurt\appdata\local\programs\python\python37\lib\site-packages\flask\sessions.py", line 375, in save_session
    val = self.get_signing_serializer(app).dumps(dict(session))
  File "c:\users\kurt\appdata\local\programs\python\python37\lib\site-packages\itsdangerous.py", line 565, in dumps
    payload = want_bytes(self.dump_payload(obj))
  File "c:\users\kurt\appdata\local\programs\python\python37\lib\site-packages\itsdangerous.py", line 847, in dump_payload
    json = super(URLSafeSerializerMixin, self).dump_payload(obj)
  File "c:\users\kurt\appdata\local\programs\python\python37\lib\site-packages\itsdangerous.py", line 550, in dump_payload
    return want_bytes(self.serializer.dumps(obj))
  File "c:\users\kurt\appdata\local\programs\python\python37\lib\site-packages\flask\json\tag.py", line 296, in dumps
    return dumps(self.tag(value), separators=(',', ':'))
  File "c:\users\kurt\appdata\local\programs\python\python37\lib\site-packages\flask\json\__init__.py", line 179, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "c:\users\kurt\appdata\local\programs\python\python37\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "c:\users\kurt\appdata\local\programs\python\python37\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "c:\users\kurt\appdata\local\programs\python\python37\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "c:\users\kurt\appdata\local\programs\python\python37\lib\site-packages\flask\json\__init__.py", line 81, in default
    return _json.JSONEncoder.default(self, o)
  File "c:\users\kurt\appdata\local\programs\python\python37\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type LocalProxy is not JSON serializable
2018-08-05 18:09:02,860 Kurtain Startup [in C:\Users\kurt\Python\kurtain\kurtain\__init__.py:42]
2018-08-05 18:17:36,343 Kurtain Startup [in C:\Users\kurt\Python\kurtain\kurtain\__init__.py:42]
2018-08-05 18:18:24,004 Kurtain Startup [in C:\Users\kurt\Python\kurtain\kurtain\__init__.py:42]
2018-08-05 18:18:58,391 Kurtain Startup [in C:\Users\kurt\Python\kurtain\kurtain\__init__.py:42]
2018-08-05 18:19:02,746 Exception on /edit_profile [POST] [in c:\users\kurt\appdata\local\programs\python\python37\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\kurt\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\kurt\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\kurt\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\kurt\appdata\local\programs\python\python37\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\kurt\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\kurt\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\kurt\appdata\local\programs\python\python37\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\kurt\Python\kurtain\kurtain\routes.py", line 76, in edit_profile
    return redirect(url_for('user', username = username))
NameError: name 'username' is not defined
2018-08-05 18:20:37,815 Kurtain Startup [in C:\Users\kurt\Python\kurtain\kurtain\__init__.py:42]
2018-08-05 18:33:09,344 Kurtain Startup [in C:\Users\kurt\Python\kurtain\kurtain\__init__.py:42]
