2018-08-05 16:54:09,652 Kurtain Startup [in C:\Users\kurt\Python\kurtain\kurtain\__init__.py:42]
2018-08-05 17:06:33,598 Kurtain Startup [in C:\Users\kurt\Python\kurtain\kurtain\__init__.py:42]
2018-08-05 17:06:49,139 Exception on /follow/susan [GET] [in c:\users\kurt\appdata\local\programs\python\python37\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\kurt\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\kurt\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "c:\users\kurt\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1831, in finalize_request
    response = self.make_response(rv)
  File "c:\users\kurt\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1957, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2018-08-05 17:11:36,088 Exception on /follow/susan [GET] [in c:\users\kurt\appdata\local\programs\python\python37\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\kurt\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\kurt\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "c:\users\kurt\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1831, in finalize_request
    response = self.make_response(rv)
  File "c:\users\kurt\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1957, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2018-08-05 17:14:01,120 Exception on /follow/susan [GET] [in c:\users\kurt\appdata\local\programs\python\python37\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\kurt\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\kurt\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "c:\users\kurt\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1831, in finalize_request
    response = self.make_response(rv)
  File "c:\users\kurt\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1957, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2018-08-05 17:14:32,866 Exception on /follow/susan [GET] [in c:\users\kurt\appdata\local\programs\python\python37\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\kurt\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\kurt\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "c:\users\kurt\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1831, in finalize_request
    response = self.make_response(rv)
  File "c:\users\kurt\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1957, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2018-08-05 17:14:42,103 Kurtain Startup [in C:\Users\kurt\Python\kurtain\kurtain\__init__.py:42]
2018-08-05 17:14:48,826 Exception on /follow/susan [GET] [in c:\users\kurt\appdata\local\programs\python\python37\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\kurt\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\kurt\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "c:\users\kurt\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1831, in finalize_request
    response = self.make_response(rv)
  File "c:\users\kurt\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1957, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2018-08-05 17:15:25,971 Kurtain Startup [in C:\Users\kurt\Python\kurtain\kurtain\__init__.py:42]
2018-08-05 17:15:30,088 Exception on /follow/susan [GET] [in c:\users\kurt\appdata\local\programs\python\python37\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\kurt\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\kurt\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "c:\users\kurt\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1831, in finalize_request
    response = self.make_response(rv)
  File "c:\users\kurt\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1957, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2018-08-05 17:16:39,841 Kurtain Startup [in C:\Users\kurt\Python\kurtain\kurtain\__init__.py:42]
2018-08-05 17:18:08,733 Kurtain Startup [in C:\Users\kurt\Python\kurtain\kurtain\__init__.py:42]
2018-08-05 17:18:11,767 Exception on /edit_profile [GET] [in c:\users\kurt\appdata\local\programs\python\python37\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\kurt\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\kurt\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\kurt\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\kurt\appdata\local\programs\python\python37\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\kurt\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\kurt\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\kurt\appdata\local\programs\python\python37\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\kurt\Python\kurtain\kurtain\routes.py", line 80, in edit_profile
    return render_template('user.html', title='Profile', form=form)
  File "c:\users\kurt\appdata\local\programs\python\python37\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "c:\users\kurt\appdata\local\programs\python\python37\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "c:\users\kurt\appdata\local\programs\python\python37\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "c:\users\kurt\appdata\local\programs\python\python37\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "c:\users\kurt\appdata\local\programs\python\python37\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\kurt\appdata\local\programs\python\python37\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\kurt\Python\kurtain\kurtain\templates\user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\kurt\Python\kurtain\kurtain\templates\base.html", line 43, in top-level template code
    {% block content %}{% endblock %}
  File "C:\Users\kurt\Python\kurtain\kurtain\templates\user.html", line 6, in block "content"
    <td><img src="{{ user.avatar(128) }}"></td>
  File "c:\users\kurt\appdata\local\programs\python\python37\lib\site-packages\jinja2\environment.py", line 430, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'user' is undefined
2018-08-05 17:18:58,620 Kurtain Startup [in C:\Users\kurt\Python\kurtain\kurtain\__init__.py:42]
