2018-08-06 19:07:02,152 Exception on /favicon.ico [GET] [in c:\users\kurt\appdata\local\programs\python\python37\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\kurt\appdata\local\programs\python\python37\lib\site-packages\sqlalchemy\util\_collections.py", line 999, in __call__
    return self.registry[key]
KeyError: 10364

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\kurt\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\kurt\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\kurt\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\kurt\appdata\local\programs\python\python37\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\kurt\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1811, in full_dispatch_request
    rv = self.preprocess_request()
  File "c:\users\kurt\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 2087, in preprocess_request
    rv = func()
  File "C:\Users\kurt\Python\kurtain\kurtain\routes.py", line 74, in before_request
    if current_user.is_authenticated:
  File "c:\users\kurt\appdata\local\programs\python\python37\lib\site-packages\werkzeug\local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
  File "c:\users\kurt\appdata\local\programs\python\python37\lib\site-packages\werkzeug\local.py", line 306, in _get_current_object
    return self.__local()
  File "c:\users\kurt\appdata\local\programs\python\python37\lib\site-packages\flask_login\utils.py", line 26, in <lambda>
    current_user = LocalProxy(lambda: _get_user())
  File "c:\users\kurt\appdata\local\programs\python\python37\lib\site-packages\flask_login\utils.py", line 335, in _get_user
    current_app.login_manager._load_user()
  File "c:\users\kurt\appdata\local\programs\python\python37\lib\site-packages\flask_login\login_manager.py", line 359, in _load_user
    return self.reload_user()
  File "c:\users\kurt\appdata\local\programs\python\python37\lib\site-packages\flask_login\login_manager.py", line 321, in reload_user
    user = self.user_callback(user_id)
  File "C:\Users\kurt\Python\kurtain\kurtain\models.py", line 82, in load_user
    return User.query.get(int(id))
  File "c:\users\kurt\appdata\local\programs\python\python37\lib\site-packages\flask_sqlalchemy\__init__.py", line 514, in __get__
    return type.query_class(mapper, session=self.sa.session())
  File "c:\users\kurt\appdata\local\programs\python\python37\lib\site-packages\sqlalchemy\orm\scoping.py", line 74, in __call__
    return self.registry()
  File "c:\users\kurt\appdata\local\programs\python\python37\lib\site-packages\sqlalchemy\util\_collections.py", line 1001, in __call__
    return self.registry.setdefault(key, self.createfunc())
  File "c:\users\kurt\appdata\local\programs\python\python37\lib\site-packages\sqlalchemy\orm\session.py", line 2950, in __call__
    return self.class_(**local_kw)
  File "c:\users\kurt\appdata\local\programs\python\python37\lib\site-packages\flask_sqlalchemy\__init__.py", line 143, in __init__
    bind = options.pop('bind', None) or db.engine
  File "c:\users\kurt\appdata\local\programs\python\python37\lib\site-packages\flask_sqlalchemy\__init__.py", line 877, in engine
    return self.get_engine()
  File "c:\users\kurt\appdata\local\programs\python\python37\lib\site-packages\flask_sqlalchemy\__init__.py", line 896, in get_engine
    return connector.get_engine()
  File "c:\users\kurt\appdata\local\programs\python\python37\lib\site-packages\flask_sqlalchemy\__init__.py", line 556, in get_engine
    self._sa.apply_driver_hacks(self._app, info, options)
  File "c:\users\kurt\appdata\local\programs\python\python37\lib\site-packages\flask_sqlalchemy\__init__.py", line 830, in apply_driver_hacks
    if info.drivername.startswith('mysql'):
AttributeError: 'NoneType' object has no attribute 'drivername'
2018-08-06 19:08:33,780 Kurtain Startup [in C:\Users\kurt\Python\kurtain\kurtain\__init__.py:44]
2018-08-06 19:09:14,126 Kurtain Startup [in C:\Users\kurt\Python\kurtain\kurtain\__init__.py:44]
2018-08-06 19:09:16,064 Exception on /index [GET] [in c:\users\kurt\appdata\local\programs\python\python37\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\kurt\appdata\local\programs\python\python37\lib\site-packages\sqlalchemy\util\_collections.py", line 999, in __call__
    return self.registry[key]
KeyError: 9696

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\kurt\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\kurt\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\kurt\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\kurt\appdata\local\programs\python\python37\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\kurt\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1811, in full_dispatch_request
    rv = self.preprocess_request()
  File "c:\users\kurt\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 2087, in preprocess_request
    rv = func()
  File "C:\Users\kurt\Python\kurtain\kurtain\routes.py", line 74, in before_request
    if current_user.is_authenticated:
  File "c:\users\kurt\appdata\local\programs\python\python37\lib\site-packages\werkzeug\local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
  File "c:\users\kurt\appdata\local\programs\python\python37\lib\site-packages\werkzeug\local.py", line 306, in _get_current_object
    return self.__local()
  File "c:\users\kurt\appdata\local\programs\python\python37\lib\site-packages\flask_login\utils.py", line 26, in <lambda>
    current_user = LocalProxy(lambda: _get_user())
  File "c:\users\kurt\appdata\local\programs\python\python37\lib\site-packages\flask_login\utils.py", line 335, in _get_user
    current_app.login_manager._load_user()
  File "c:\users\kurt\appdata\local\programs\python\python37\lib\site-packages\flask_login\login_manager.py", line 359, in _load_user
    return self.reload_user()
  File "c:\users\kurt\appdata\local\programs\python\python37\lib\site-packages\flask_login\login_manager.py", line 321, in reload_user
    user = self.user_callback(user_id)
  File "C:\Users\kurt\Python\kurtain\kurtain\models.py", line 82, in load_user
    return User.query.get(int(id))
  File "c:\users\kurt\appdata\local\programs\python\python37\lib\site-packages\flask_sqlalchemy\__init__.py", line 514, in __get__
    return type.query_class(mapper, session=self.sa.session())
  File "c:\users\kurt\appdata\local\programs\python\python37\lib\site-packages\sqlalchemy\orm\scoping.py", line 74, in __call__
    return self.registry()
  File "c:\users\kurt\appdata\local\programs\python\python37\lib\site-packages\sqlalchemy\util\_collections.py", line 1001, in __call__
    return self.registry.setdefault(key, self.createfunc())
  File "c:\users\kurt\appdata\local\programs\python\python37\lib\site-packages\sqlalchemy\orm\session.py", line 2950, in __call__
    return self.class_(**local_kw)
  File "c:\users\kurt\appdata\local\programs\python\python37\lib\site-packages\flask_sqlalchemy\__init__.py", line 143, in __init__
    bind = options.pop('bind', None) or db.engine
  File "c:\users\kurt\appdata\local\programs\python\python37\lib\site-packages\flask_sqlalchemy\__init__.py", line 877, in engine
    return self.get_engine()
  File "c:\users\kurt\appdata\local\programs\python\python37\lib\site-packages\flask_sqlalchemy\__init__.py", line 896, in get_engine
    return connector.get_engine()
  File "c:\users\kurt\appdata\local\programs\python\python37\lib\site-packages\flask_sqlalchemy\__init__.py", line 556, in get_engine
    self._sa.apply_driver_hacks(self._app, info, options)
  File "c:\users\kurt\appdata\local\programs\python\python37\lib\site-packages\flask_sqlalchemy\__init__.py", line 830, in apply_driver_hacks
    if info.drivername.startswith('mysql'):
AttributeError: 'NoneType' object has no attribute 'drivername'
2018-08-06 19:10:00,753 Kurtain Startup [in C:\Users\kurt\Python\kurtain\kurtain\__init__.py:44]
